TICKER_KEY = 'Ticker'
TICKER_KEY_CAPITAL = 'TICKER'
COMPANY_KEY = 'Company'
COMPANY_KEY_CAPITAL = 'COMPANY'
DEFAULT_DATE_FORMAT="%Y-%m-%d"
DAYS_TO_EARNINGS_KEY_CAPITAL='DAYS_LEFT'
DAYS_TO_EARNINGS_KEY_BEFORE_FORMAT='days_left'
DEFAULT_DAYS_PRE_EARNINGS = 5

MARKET_DATA_TICKERS = ['^GSPC', '^TNX', '^RUT', '^VIX']
TBILL_10_YEAR = '^TNX'

ALPHAVANTAGE_EARNINGS_DATE_KEY = 'reportDate'
DAYS_TO_EARNINGS_KEY='days_left'  # in lower case betcause this is used before formatting
SYMBOL_KEY = 'symbol'

FINVIZ_EARNINGS_DATE_KEY = 'EARNINGS_DATE'
DAYS_LEFT_KEY = 'DAYS_LEFT'
ALLOWED_CAPITALIZATIONS = ['micro', 'small', 'medium']

# Post processing fields 
ABS_RET_KEY='1+{}_RET'
EXP_RET_KEY='EXP.RET_{}'
BETA_KEY='BETA'
RF_KEY='1+{}_RF'
SP_500_TICKER='^GSPC'
MARK_EXP_KEY='MARK_EXP_{}'
CAPM_KEY='CAPM_{}'
TBILL_10_YEAR='^TNX'
VIX_TICKER='^VIX'
VIX_KEY='1+{}_VIX'
EARNING_VIX_KEY='EARNING_VIX'
CAR_KEY='CAR_{}'
BHAR_KEY='BHAR_{}'
DATADATE_KEY='DATADATE'
ALLOWED_WINDOWS = [3, 30, 60]