CUSTOM_TABLE_FIELDS_ON_URL = """&c=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,75,16,
77,17,18,19,20,21,23,22,82,78,127,128,24,25,85,26,27,28,29,30,31,84,32,33,34,35,36,37,
38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,57,58,59,68,69,73,74,76,79,80,81,
83,62,63,64,67,65,66,120,130,131,132,133,134"""


CUSTOM_TABLE_ALL_FIELDS_NEW = [
    'Ticker',
    'Company',
    'Sector',
    'Industry',
    'Country',
    'Market Cap',
    'P/E',
    'Fwd P/E',
    'PEG',
    'P/S',
    'P/B',
    'P/C',
    'P/FCF',
    'Dividend',
    'Payout Ratio',
    'EPS',
    'EPS next Q',
    'EPS this Y',
    'EPS next Y',
    'EPS past 5Y',
    'EPS next 5Y',
    'Sales past 5Y',
    'Sales Q/Q',
    'Sales YoY TTM',
    'EPS Q/Q',
    'Sales',
    'Income',
    'EPS Surprise',
    'Revenue Surprise',
    'Outstanding',
    'Float',
    'Float %',
    'Insider Own',
    'Insider Trans',
    'Inst Own',
    'Inst Trans',
    'Short Float',
    'Short Ratio',
    'Short Interest',
    'ROA',
    'ROE',
    'ROI',
    'Curr R',
    'Quick R',
    'LTDebt/Eq',
    'Debt/Eq',
    'Gross M',
    'Oper M',
    'Profit M',
    'Perf Week',
    'Perf Month',
    'Perf Quart',
    'Perf Half',
    'Perf Year',
    'Perf YTD',
    'Beta',
    'ATR',
    'Volatility W',
    'Volatility M',
    'SMA20',
    'SMA50',
    'SMA200',
    '52W High',
    '52W Low',
    'RSI',
    'Earnings',
    'Target Price',
    'Book/sh',
    'Cash/sh',
    'Employees',
    'Index',
    'Optionable',
    'Prev Close',
    'Shortable',
    'Recom',
    'Avg Volume',
    'Rel Volume',
    'Volume',
    'Price',
    'Change',
    'Return% 1Y',
    'Dividend TTM',
    'Dividend Ex Date',
    'EPS YoY TTM',
    'EPS YoY TTM',
    '52W Range'
]

POST_GENERATED_FIELDS = [
    '52W_NORM',
    'LTDEBT/EQ',
    'DIVIDEND_YIELD_EST',
    'DIVIDEND_YIELD_TTM',
    'IS_S&P500',
    'IS_RUSSELL',
    'IS_NASDAQ',
    'IS_AMC',
    'IS_BMO',
    'DIVIDEND_EX-DATE',
    'IS_OPTIONABLE',
    'IS_SHORTABLE',
    'VOLATILITY_RANGE',
    'IS_USA',
]


MONEY_COLUMNS = [
    'Avg Volume', 
    'Outstanding',
    'Market Cap',
    'Float',
    'Income',
    'Sales',
    'Short Interest',
    'Outstanding',
    'Float'
]

PERCENTAJE_COLUMNS = [
    'Perf Week', 
    'Perf Month', 
    'Perf Quart', 
    'Perf Year', 
    'Perf YTD', 
    'Volatility W', 
    'Volatility M', 
    'Change', 
    'Insider Own',
    'EPS next Y',
    'Insider Trans',
    'Inst Own',
    'Perf Quart',
    'EPS this Y',
    'Inst Trans',
    'Perf Half',
    'ROA',
    'EPS next 5Y',
    'ROE',
    'EPS past 5Y',
    'ROI',
    '52W High',
    'Sales past 5Y',
    'Gross M',
    '52W Low',
    'Sales Q/Q',
    'Oper M',
    'EPS Q/Q',
    'Profit M',
    'Payout Ratio',
    'SMA20',
    'SMA50',
    'SMA200',
    'Dividend',
    'Payout Ratio',
    'EPS Surprise',
    'Revenue Surprise',
    'Float %',
    'Oper M',
    'Profit M',
    'Short Float',
    'EPS YoY TTM',
    'Sales YoY TTM',
]

NUMERIC_COLUMNS = [
    'P/FCF',
    'Beta',
    'EPS YoY TTM',
    'ATR',
    'Employees',
    'Curr R',
    'Quick R',
    'RSI',
    'Debt/Eq',
    'LTDebt/Eq',
    'Recom',
    'Rel Volume',
    'Price',
    'Volume',
    'P/E',
    'Fwd P/E',
    'PEG',
    'P/S',
    'Book/sh',
    'P/B',
    'Target Price',
    'Cash/sh',
    'P/C',
    'EPS next Q',
    'Fwd P/E',
    'EPS',
    'Short Ratio',
    'Short Interest',
    'RSI',
    'Avg Volume',
    'Return% 1Y',
    'Outstanding',
    'Float',
    'ATR',
    'Prev Close',
]

BOOLEAN_COLUMNS = [
    'Optionable',
    'Shortable'
]

ALLOWED_INDUSTRIES = [
    "Advertising Agencies",
    "Aerospace & Defense",
    "Agricultural Inputs",
    "Airlines",
    "Airports & Air Services",
    "Aluminum",
    "Apparel Manufacturing",
    "Apparel Retail",
    "Asset Management",
    "Auto Manufacturers",
    "Auto Parts",
    "Auto & Truck Dealerships",
    "Banks - Diversified",
    "Banks - Regional",
    "Beverages - Brewers",
    "Beverages - Non-Alcoholic",
    "Beverages - Wineries & Distilleries",
    "Biotechnology",
    "Broadcasting",
    "Building Materials",
    "Building Products & Equipment",
    "Business Equipment & Supplies",
    "Capital Markets",
    "Chemicals",
    "Coking Coal",
    "Communication Equipment",
    "Computer Hardware",
    "Confectioners",
    "Conglomerates",
    "Consulting Services",
    "Consumer Electronics",
    "Copper",
    "Credit Services",
    "Department Stores",
    "Diagnostics & Research",
    "Discount Stores",
    "Drug Manufacturers - General",
    "Drug Manufacturers - Specialty & Generic",
    "Education & Training Services",
    "Electrical Equipment & Parts",
    "Electronic Components",
    "Electronic Gaming & Multimedia",
    "Electronics & Computer Distribution",
    "Engineering & Construction",
    "Entertainment",
    "Farm & Heavy Construction Machinery",
    "Farm Products",
    "Financial Conglomerates",
    "Financial Data & Stock Exchanges",
    "Food Distribution",
    "Footwear & Accessories",
    "Furnishings, Fixtures & Appliances",
    "Gambling",
    "Gold",
    "Grocery Stores",
    "Healthcare Plans",
    "Health Information Services",
    "Home Improvement Retail",
    "Household & Personal Products",
    "Industrial Distribution",
    "Information Technology Services",
    "Infrastructure Operations",
    "Insurance Brokers",
    "Insurance - Diversified",
    "Insurance - Life",
    "Insurance - Property & Casualty",
    "Insurance - Reinsurance",
    "Insurance - Specialty",
    "Integrated Freight & Logistics",
    "Internet Content & Information",
    "Internet Retail",
    "Leisure",
    "Lodging",
    "Lumber & Wood Production",
    "Luxury Goods",
    "Marine Shipping",
    "Medical Care Facilities",
    "Medical Devices",
    "Medical Distribution",
    "Medical Instruments & Supplies",
    "Metal Fabrication",
    "Mortgage Finance",
    "Oil & Gas Drilling",
    "Oil & Gas E&P",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Integrated",
    "Oil & Gas Midstream",
    "Oil & Gas Refining & Marketing",
    "Other Industrial Metals & Mining",
    "Other Precious Metals & Mining",
    "Packaged Foods",
    "Packaging & Containers",
    "Paper & Paper Products",
    "Personal Services",
    "Pharmaceutical Retailers",
    "Pollution & Treatment Controls",
    "Publishing",
    "Railroads",
    "Real Estate - Development",
    "Real Estate - Diversified",
    "Real Estate Services",
    "Recreational Vehicles",
    "REIT - Diversified",
    "REIT - Healthcare Facilities",
    "REIT - Hotel & Motel",
    "REIT - Industrial",
    "REIT - Mortgage",
    "REIT - Office",
    "REIT - Residential",
    "REIT - Retail",
    "REIT - Specialty",
    "Rental & Leasing Services",
    "Residential Construction",
    "Resorts & Casinos",
    "Restaurants",
    "Scientific & Technical Instruments",
    "Security & Protection Services",
    "Semiconductor Equipment & Materials",
    "Semiconductors",
    "Shell Companies",
    "Silver",
    "Software - Application",
    "Software - Infrastructure",
    "Solar",
    "Specialty Business Services",
    "Specialty Chemicals",
    "Specialty Industrial Machinery",
    "Specialty Retail",
    "Staffing & Employment Services",
    "Steel",
    "Telecom Services",
    "Textile Manufacturing",
    "Thermal Coal",
    "Tobacco",
    "Tools & Accessories",
    "Travel Services",
    "Trucking",
    "Uranium",
    "Utilities - Diversified",
    "Utilities - Independent Power Producers",
    "Utilities - Regulated Electric",
    "Utilities - Regulated Gas",
    "Utilities - Regulated Water",
    "Utilities - Renewable",
    "Waste Management"
]

TICKER_KEY = 'Ticker'