name: Bump Version on Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'earningspy/__version__.py'
      - '.bumpversion.cfg'
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set git user (App identity)
        run: |
          git config --global user.name "GitHub App"
          git config --global user.email "app@example.com"

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version (patch)
        run: |
          bump2version patch --allow-dirty --message "Bump version to {new_version} [skip ci]"
          git status
          git add .
          git push origin master --tags
