name: Publish Wheel to PyPi

on:
  workflow_dispatch:

jobs:
  upload-wheel:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up build dependencies
        run: pip install setuptools wheel twine
  
      - name: Build wheel
        run: python setup.py bdist_wheel
  
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
  
  create-release:
    runs-on: ubuntu-latest
    needs: [upload-wheel] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Get latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  